name: Continuous Integration (CI)

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make all
      run: make all
    - name: make check
      run: make check
    - name: make leak-test
      run: make leak-test